site_name: My Docs
site_url: https://psmodule.io/docs-test/
theme:
  name: material
  features:
    - content.code.copy
extra:
  version:
    provider: mike
    alias: true
plugins:
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
