name: ci
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0         # mike needs history
          persist-credentials: true

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - uses: PSModule/GitHub-Script@v1
        with:
          Script: |
            pip install mkdocs mkdocs-material mike
            mike deploy --push --update-aliases 0.16 latest
            mike set-default --push latest
