name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0         # mike needs history
          persist-credentials: true

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - uses: PSModule/GitHub-Script@v1
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          Script: |
            pip install mkdocs mkdocs-material mike

            if ($env:GITHUB_EVENT_NAME -eq 'pull_request') {
                $event = Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json
                $action = $event.action
                $prNumber = $env:PR_NUMBER
                $version = "pr-$prNumber"
                if ($action -eq 'closed') {
                    mike delete --push $version
                } else {
                    mike deploy --push $version --prop-set hidden=true
                    gh pr comment $prNumber --body "Documentation preview available at https://psmodule.github.io/docs-test/$version/"
                }
            } else {
                mike deploy --push --update-aliases 0.3 latest
                mike set-default --push latest
            }
